### ISSUE TITLE
How to get the required model?

### ISSUE THREAD

**Issue by ibehnam** [QuangBK/localLLM_guidance#1]
I noticed you use GPTQ, but apparently it's incompatible with M1 Mac. Can you please generalize your project so that any model can be selected? Even the models that M1 Macs can run.

**Comment by QuangBK** [comment]
You can change my GPTQ with other models. Just change the `model` and` tokenizer` in my code with your model and tokenizer by modifying [this line](https://github.com/QuangBK/localLLM_guidance/blob/main/app.py#LL26C1-L26C72).
The Guidance also has several examples of using local LLMs in its document.

If you want a GGML model, they're working to support llama-cpp-python from [this](https://github.com/microsoft/guidance/pull/70).
Currently, you may want to check [this notebook](https://github.com/Maximilian-Winter/guidance/blob/main/notebooks/api_examples/llms/LlamaCpp/LlamaCpp.ipynb) from another fork.

**Comment by ibehnam** [comment]
Thank you so much!
